hotfix for inla given by Arnstein
issue = latest inla breaks package (See notes)
fixed with arnstein's hotfix by commenting out?

I’ve installed INLA 21.11.22 (last stable version) and tried to install socialFrontiers with

install_github(
  "menglezhang/socialfrontiers",
  build_opts = c("--no-resave-data", "--no-manual"),
  build_vignettes = TRUE,
  force = TRUE
  )

I get the following error building the vignettes:

─  installing the package to build vignettes
E  creating vignettes (45.2s)
   --- re-building ‘Detecting-frontiers-in-Barnet.Rmd’ using rmarkdown
   Quitting from lines 62-68 (Detecting-frontiers-in-Barnet.Rmd)
   Error: processing vignette 'Detecting-frontiers-in-Barnet.Rmd' failed with diagnostics:
   unused argument (control.results = list(return.marginals.predictor = TRUE))
   --- failed re-building ‘Detecting-frontiers-in-Barnet.Rmd’

I think something have changed in INLA. In help I find that return.marginals.predictor
 = TRUE is the default. I have edited the code in Binominal_LocalisedINLA.R and just commented out the
occurrences of
control.results = list(return.marginals.predictor = TRUE) and the code seems to run
 fine.